<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>Спасибо за регистрацию</title>
    <style>
        h1{
            color: cadetblue;
        }
        h2{
            color: lightcoral;
        }
    </style>
</head>
<body>
    <h1>Ссылка на регистрацию</h1>
    <h2><a href="${server_url}/confirm/${confirm_code}">Перейдите по ссылке</a></h2>
</body>
</html>